
language: node_js
node_js: stable
script:
  - ls
  - bash cookie-consent-polymer/gpages_build.sh zisismaras cookie-consent-polymer
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
