
language: node_js
node_js: stable
script:
  - bash ./gpages_build.sh zisismaras cookie-consent-polymer Travis contact@zisismaras.me
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
